In [2]:
import numpy as np

In [3]:
x=np.array([200,17])

def sigmoid(z):
    z=np.clip(z,-500,500)
    g=1.0/(1.0+np.exp(-z))
    return g

# first layer first neuron
w1_1=np.array([1,2])
b1_1=np.array([-1])
z1_1=np.dot(w1_1,x)+b1_1
a1_1=sigmoid(z1_1)
#first layer second neuron
w1_2=np.array([-3,4])
b1_2=np.array([1])
z1_2=np.dot(w1_2,x)+b1_2
a1_2=sigmoid(z1_2)
#first layer third neuron
w1_3=np.array([5,-6])
b1_3=np.array([2])
z1_3=np.dot(w1_3,x)+b1_3
a1_3=sigmoid(z1_3)

# sent to the next layer 
a1=np.array([a1_1,a1_2,a1_3])

#second layer first neuron
w2_1=np.array([-7,8,9])
b2_1=np.array([3])
z2_1=np.dot(w2_1,a1)+b2_1
a2_1=sigmoid(z2_1)
a2_1

array([0.99330715])

In [8]:
# for loop implementation of froward prop of NN
x=np.array([200,17])       # given in 1d array
W=np.array([[1,-3,5],    
            [-2,4,-6]])    # 2d
b=np.array([-1,1,2])       # 1d
def sigmoid(z):
    z=np.clip(z,-500,500)
    g=1.0/(1.0+np.exp(-z))
    return g
g = sigmoid
def dense(a_in,W,b):
    units=W.shape[1]
    a_out=np.zeros(units)
    for j in range(units):
        w=W[:,j]
        z=np.dot(w,a_in)+b[j]
        a_out[j]=g(z)
    return a_out    
aout=dense(x,W,b)
aout 

array([1.00000000e+000, 7.12457641e-218, 1.00000000e+000])

In [5]:
# vectorized implementation forward prop of NN 
X_t=np.array([[200,17]])    # 2-d arrays--all
W=np.array([[1,-3,5],
            [-2,4,-6]])
B=np.array([[-1,1,2]])

def dense(A_in,W,B):    
    Z=np.matmul(A_in,W)+B     # matrices multiplication
    A_out=g(Z)
    return A_out

q=dense(X_t,W,B)
q

array([[1.00000000e+000, 7.12457641e-218, 1.00000000e+000]])

In [6]:
W[0]

array([ 1, -3,  5])

In [9]:
# matrix multiplications
q=np.array([[1,2,4],
            [3,4,5]])
q.shape
q_t=q.T  # transpose
q_t
w=np.array([[3,4,5,6],
            [7,8,9,7]])

z=q_t@w # we can use z=np.matmul(q_t,w) or q_t @ w
z

array([[24, 28, 32, 27],
       [34, 40, 46, 40],
       [47, 56, 65, 59]])